/**
 * Textos de las plantillas del profesional (PF-09; DL-108). Una plantilla es un molde: los textos lo dicen y nunca
 * prometen que el plan «sale solo» ni califican nada (TEST-PRJ-009 se aplica con los términos de entrenamiento).
 */
export const COPY_PLANTILLAS = {
  misPlantillas: 'Mis plantillas',
  plantilla: 'Plantilla',
  descripcion: 'Descripción',
  nombre: 'Nombre',
  guardarComoPlantilla: 'Guardar como plantilla',
  empezarDesdePlantilla: 'Empezar desde una plantilla',
  empezarEnBlanco: 'Empezar en blanco',
  aplicar: 'Crear el borrador desde esta plantilla',
  nuevaVersion: 'Nueva versión de la plantilla',
  archivar: 'Archivar',
  reactivar: 'Reactivar',
  guardar: 'Guardar la plantilla',
  cancelar: 'Cancelar',
  activa: 'Activa',
  archivada: 'Archivada',
  sinPlantillas: 'Todavía no guardaste ninguna plantilla. Se guardan desde una versión de plan, con «Guardar como plantilla».',
  sinPlantillasActivas: 'No tenés plantillas activas para aplicar.',
  queCopia: 'La plantilla copia la estructura (bloques, sesiones, ejercicios, series, intensidad y parámetros), no a la persona: no lleva objetivo ni próxima revisión.',
  cargas: 'Conservar las cargas sugeridas como referencia de la plantilla',
  cargasAyuda: 'Apagado, las cargas no se copian: son de cada persona. Encendido, quedan en la plantilla como referencia y las revisás al aplicarla.',
  notasTitulo: 'Notas que se van a copiar',
  notasAyuda: 'Revisá que ninguna nombre a una persona ni describa su situación. Podés vaciarlas una por una.',
  vaciarNota: 'Vaciar',
  sinNotas: 'Esta versión no tiene notas de texto libre.',
  guardada: 'Plantilla guardada. La encontrás en «Mis plantillas».',
  versionCreada: 'Nueva versión guardada. Las anteriores no cambian; los planes ya creados tampoco.',
  aplicada: 'Borrador creado desde la plantilla. Adaptalo a la persona antes de activarlo: no es visible para el asesorado hasta que lo actives.',
  creadaDesde: (nombre: string, numero: number): string => `Creada desde la plantilla «${nombre}», versión ${numero}. El plan es de esta persona: la plantilla no cambia si lo editás.`,
  origenDesconocido: 'Creada desde una plantilla que ya no está disponible.',
  nombreTomado: 'Ya tenés una plantilla con ese nombre.',
  archivadaNoSeAplica: 'Esa plantilla está archivada: reactivala para usarla.',
  sesiones: (n: number): string => `${n} ${n === 1 ? 'sesión' : 'sesiones'}`,
  conCargas: 'Con cargas de referencia',
  sinCargas: 'Sin cargas',
  origen: (fecha: string): string => `Guardada desde una versión de plan el ${fecha}`,
  desdeCero: 'Escrita desde cero',
  soloTuya: 'Solo vos ves y aplicás tus plantillas. Si dejás BE, quedan inactivas; los planes ya creados no dependen de ellas.',
} as const;
