/**
 * Textos de «Mis habituales» (PF-09 bis; DL-109). Un habitual es una herramienta de trabajo del profesional: los textos
 * dicen qué copia y qué no, y nunca califican nada (TEST-PRJ-009 se aplica con los términos de entrenamiento y de
 * nutrición).
 */
export const COPY_HABITUALES = {
  misHabituales: 'Mis habituales',
  plantillasYHabituales: 'Plantillas y habituales',
  ejerciciosHabituales: 'Ejercicios habituales',
  alimentosHabituales: 'Alimentos habituales',
  sesionesHabituales: 'Sesiones habituales',
  comidasHabituales: 'Comidas habituales',
  marcar: 'Marcar como habitual',
  quitarMarca: 'Quitar de habituales',
  sinEjerciciosHabituales: 'Todavía no marcaste ejercicios habituales. Se marcan desde el buscador, con «Marcar como habitual».',
  sinAlimentosHabituales: 'Todavía no marcaste alimentos habituales. Se marcan desde el buscador, con «Marcar como habitual».',
  guardarComoHabitual: 'Guardar como habitual',
  agregarSesion: 'Agregar una sesión habitual',
  agregarComida: 'Agregar una comida habitual',
  insertarSesion: 'Agregar esta sesión habitual',
  insertarComida: 'Agregar esta comida habitual',
  sinSesiones: 'Todavía no guardaste sesiones habituales. Se guardan desde una sesión del editor, con «Guardar como habitual».',
  sinComidas: 'Todavía no guardaste comidas habituales. Se guardan desde una comida del editor, con «Guardar como habitual».',
  queCopiaSesion: 'La sesión habitual copia los ejercicios, las series, la intensidad y los parámetros, no a la persona. Al agregarla a un borrador pasa a ser de ese plan.',
  queCopiaComida: 'La comida habitual copia las opciones y los alimentos, no a la persona: no lleva cantidades. Al agregarla a un borrador pasa a ser de ese plan.',
  cargas: 'Conservar las cargas sugeridas como referencia',
  cargasAyuda: 'Apagado, las cargas no se copian: son de cada persona. Encendido, quedan en la sesión habitual como referencia y las revisás al agregarla.',
  cantidades: 'Conservar las cantidades como referencia',
  cantidadesAyuda: 'Apagado, las cantidades no se copian: son de cada persona. Encendido, quedan en la comida habitual como referencia y las revisás al agregarla.',
  notasTitulo: 'Notas que se van a copiar',
  notasAyuda: 'Revisá que ninguna nombre a una persona ni describa su situación. Podés vaciarlas una por una.',
  vaciarNota: 'Vaciar',
  sinNotas: 'No tiene notas de texto libre.',
  nombre: 'Nombre',
  guardarSesion: 'Guardar la sesión habitual',
  guardarComida: 'Guardar la comida habitual',
  reemplazar: 'Reemplazar',
  cancelar: 'Cancelar',
  seReemplazaSesion: (nombre: string): string => `Ya tenés una sesión habitual «${nombre}»: se reemplaza por esta.`,
  seReemplazaComida: (nombre: string): string => `Ya tenés una comida habitual «${nombre}»: se reemplaza por esta.`,
  guardadaSesion: 'Sesión habitual guardada. La encontrás en «Agregar una sesión habitual» y en «Plantillas y habituales».',
  guardadaComida: 'Comida habitual guardada. La encontrás en «Agregar una comida habitual» y en «Plantillas y habituales».',
  insertadaSesion: 'Sesión habitual agregada al borrador. Es de este plan: revisá las cargas y las notas.',
  insertadaComida: 'Comida habitual agregada al borrador. Es de este plan: revisá las cantidades y las notas.',
  quitado: 'Habitual quitado.',
  renombrar: 'Renombrar',
  quitar: 'Quitar',
  ejercicios: (n: number): string => `${n} ${n === 1 ? 'ejercicio' : 'ejercicios'}`,
  alimentos: (n: number): string => `${n} ${n === 1 ? 'alimento' : 'alimentos'}`,
  conCargas: 'Con cargas de referencia',
  sinCargas: 'Sin cargas',
  conCantidades: 'Con cantidades de referencia',
  sinCantidades: 'Sin cantidades',
  actualizada: (fecha: string): string => `Guardada el ${fecha}`,
  soloTuyos: 'Solo vos ves tus habituales. Lo que agregás a un borrador queda en ese plan y no cambia si después editás el habitual.',
  nombreTomado: 'Ya tenés un habitual con ese nombre.',
  elementoNoDisponible: 'Ya no está disponible en el catálogo.',
} as const;
