/**
 * OpenAPI 3.1 generado desde los schemas de contrato (09v7 T21: «No se permite mantener manualmente otra definición
 * equivalente»). `scripts/generar-openapi.cjs` lo escribe en `docs/api/openapi.json` y la CI falla si difiere.
 * Alcance:
 * - las operaciones autorizadas de WP-02 (docs/paquetes/WP-02.md §4);
 * - las de WP-03 (docs/paquetes/WP-03.md §4);
 * - las de WP-04 (docs/paquetes/WP-04.md §4);
 * - las de WP-05: la familia ANT y el patrón transversal MTH/CAL (docs/paquetes/WP-05.md §4);
 * - las de WP-06: la familia TRN, la carga manual de ejercicios y la lectura por período (docs/paquetes/WP-06.md §4).
 * - las de WP-07: la familia FRM, transversal a los tres dominios (docs/paquetes/WP-07.md §4).
 */
import { z } from 'zod';
import {
  CodigoDeError,
  ErrorEnvelopeSchema,
  IniciarSesionRequestSchema,
  IniciarSesionResponseSchema,
  MeResponseSchema,
  RegistrarIdentidadRequestSchema,
  RegistrarIdentidadResponseSchema,
  RequisitoDeConsentimientoDeSaludResponseSchema,
  SolicitarCierreRequestSchema,
  SolicitarCierreResponseSchema,
} from './contratos';
import {
  AceptarSolicitudResponseSchema,
  ConsentimientoDeSaludOtorgadoResponseSchema,
  ConsentimientoOtorgadoResponseSchema,
  ConsentimientoRevocadoResponseSchema,
  CrearSolicitudDeVinculoRequestSchema,
  CrearSolicitudDeVinculoResponseSchema,
  DashboardResponseSchema,
  DecidirSolicitudRequestSchema,
  DetalleDeVinculoResponseSchema,
  FinalizarVinculoRequestSchema,
  HistorialDeConsentimientoDeSaludResponseSchema,
  ListaDeConsentimientosResponseSchema,
  ListaDeSolicitudesResponseSchema,
  ListaDeVinculosResponseSchema,
  OtorgarConsentimientoDeSaludRequestSchema,
  OtorgarConsentimientoRequestSchema,
  PausarVinculoRequestSchema,
  ReanudarVinculoRequestSchema,
  RechazarSolicitudResponseSchema,
  RequisitosDeConsentimientoResponseSchema,
  SolicitudDeduplicadaResponseSchema,
  VinculoResponseSchema,
} from './contratos-vinculo';
import {
  CandidatoDeAlimentoResponseSchema,
  CandidatoDeEjercicioResponseSchema,
  CrearCandidatoDeAlimentoRequestSchema,
  CrearCandidatoDeEjercicioRequestSchema,
  ResolucionDeAlimentoResponseSchema,
  ResolucionDeEjercicioResponseSchema,
  ResolverCandidatoDeAlimentoRequestSchema,
  ResolverCandidatoDeEjercicioRequestSchema,
} from './contratos-integraciones';
import {
  ActivacionDePlanResponseSchema,
  AplicarRevisionResponseSchema,
  ContextoDeRevisionResponseSchema,
  CorregirIngestaRequestSchema,
  CrearElementoDeCatalogoRequestSchema,
  CrearEvaluacionRequestSchema,
  CrearEvaluacionResponseSchema,
  CrearObjetivoRequestSchema,
  CrearPlanRequestSchema,
  EditarBorradorRequestSchema,
  ElementoDeCatalogoResponseSchema,
  EvaluacionResponseSchema,
  HoyResponseSchema,
  IngestaResponseSchema,
  ListaDeCatalogoResponseSchema,
  ListaDeEvaluacionesResponseSchema,
  ListaDeIngestasResponseSchema,
  ListaDeObjetivosResponseSchema,
  ListaDePlanesResponseSchema,
  ObjetivoEfectivoResponseSchema,
  ObjetivoResponseSchema,
  PlanResponseSchema,
  RegistrarIngestaRequestSchema,
  RegistrarRevisionRequestSchema,
  RevisionResponseSchema,
  ValidacionDePlanResponseSchema,
  VersionEsperadaRequestSchema,
} from './contratos-nutricion';
import {
  AnularMedicionRequestSchema,
  AnularMedicionResponseSchema,
  CorregirMedicionRequestSchema,
  CrearBorradorRequestSchema,
  CrearEvaluacionAntropometricaRequestSchema,
  EvaluacionAntropometricaResponseSchema,
  EvolucionResponseSchema,
  GuardarBorradorRequestSchema,
  ListaDeEspecificacionesResponseSchema,
  ListaDeEvaluacionesAntropometricasResponseSchema,
  MedicionSchema,
  RegistrarEvaluacionRequestSchema,
} from './contratos-antropometria';
import {
  AdoptarReferenciaRequestSchema,
  CorridaResponseSchema,
  EjecutarCalculoRequestSchema,
  ListaDeCorridasResponseSchema,
  ListaDeMetodosResponseSchema,
  MetodoResponseSchema,
  ReferenciaResponseSchema,
} from './contratos-calculo';
import {
  AbrirBorradorDeEjecucionRequestSchema,
  ActivacionDePlanDeEntrenamientoResponseSchema,
  BorradorDeEjecucionResponseSchema,
  ConfirmacionDeEjecucionResponseSchema,
  ContextoDeRevisionDeEntrenamientoResponseSchema,
  CorregirEjecucionRequestSchema,
  CrearEjercicioRequestSchema,
  CrearEvaluacionDeEntrenamientoRequestSchema,
  CrearObjetivoDeEntrenamientoRequestSchema,
  CrearPlanDeEntrenamientoRequestSchema,
  EditarBorradorDeEjecucionRequestSchema,
  EditarPlanDeEntrenamientoRequestSchema,
  EjecucionDeEntrenamientoResponseSchema,
  EjercicioDeCatalogoResponseSchema,
  EvaluacionDeEntrenamientoResponseSchema,
  HoyDeEntrenamientoResponseSchema,
  ListaDeEjerciciosResponseSchema,
  ListaDeEvaluacionesDeEntrenamientoResponseSchema,
  ListaDeObjetivosDeEntrenamientoResponseSchema,
  ListaDePlanesDeEntrenamientoResponseSchema,
  ObjetivoDeEntrenamientoEfectivoResponseSchema,
  ObjetivoDeEntrenamientoResponseSchema,
  HistorialDeEntrenamientoResponseSchema,
  OcurrenciasDelPeriodoResponseSchema,
  PlanDeEntrenamientoResponseSchema,
  RegistrarRevisionDeEntrenamientoRequestSchema,
  RevisionDeEntrenamientoResponseSchema,
} from './contratos-entrenamiento';
import {
  CrearSolicitudDeFormularioRequestSchema,
  DetalleDeSolicitudResponseSchema,
  EnviarRespuestaRequestSchema,
  ListaDePlantillasResponseSchema,
  ListaDeSolicitudesPropiasResponseSchema,
  ListaDeSolicitudesDeFormularioResponseSchema,
  RectificacionCreadaResponseSchema,
  RectificarRespuestaRequestSchema,
  RespuestaCreadaResponseSchema,
  SolicitudDeFormularioCreadaResponseSchema,
  VersionDePlantillaResponseSchema,
} from './contratos-formularios';

type Codigo = keyof typeof CodigoDeError;
type Errores = Partial<Record<400 | 401 | 403 | 404 | 409 | 422 | 429 | 500 | 503, readonly Codigo[]>>;

interface ParametroDeQuery {
  readonly nombre: string;
  readonly descripcion: string;
  readonly schema: Record<string, unknown>;
  /** Casi toda query es un filtro opcional; la que el servidor exige lo declara (sin ella responde 400). */
  readonly obligatorio?: boolean;
}

export interface Operacion {
  readonly id: string;
  readonly metodo: 'get' | 'post' | 'patch' | 'put' | 'delete';
  /** Relativa a `/api/v1`. Los parámetros de ruta van entre llaves: `/relationships/{relationshipId}`. */
  readonly ruta: string;
  readonly resumen: string;
  readonly autenticacion: 'PUBLIC' | 'SESSION' | 'SESSION_STEP_UP';
  readonly idempotencia: boolean;
  readonly request?: z.ZodType;
  /** Un cuerpo que el servidor también acepta ausente (API-TRN-15: el 09 no le declara cuerpo). */
  readonly requestOpcional?: boolean;
  readonly query?: readonly ParametroDeQuery[];
  /** El primero es el éxito principal. REL-01 y CON-02 también responden 200 (deduplicado o replay). */
  readonly exitos: readonly { readonly status: 200 | 201 | 204; readonly schema?: z.ZodType }[];
  readonly errores: Errores;
  readonly fuente: string;
}

const COMUNES: Errores = { 500: ['INTERNAL_ERROR'], 503: ['DB_UNAVAILABLE'] };

/** Los errores de una operación con los comunes **sumados**: un 503 propio (WP-08) no pisa ni es pisado por DB_UNAVAILABLE. */
function conComunes(errores: Errores): Record<string, readonly Codigo[]> {
  const todos: Record<string, readonly Codigo[]> = { ...errores };
  for (const [status, codigos] of Object.entries(COMUNES)) todos[status] = [...new Set([...(todos[status] ?? []), ...(codigos ?? [])])];
  return todos;
}
const SESION: Errores = { 401: ['AUTHENTICATION_REQUIRED', 'SESSION_INVALID', 'SESSION_EXPIRED', 'SESSION_REVOKED'] };

const LIMIT: ParametroDeQuery = { nombre: 'limit', descripcion: 'Tamaño de página (1 a 50; 20 por defecto).', schema: { type: 'integer', minimum: 1, maximum: 50 } };
const CURSOR: ParametroDeQuery = { nombre: 'cursor', descripcion: 'Cursor opaco de la página siguiente.', schema: { type: 'string' } };
const ALCANCE: ParametroDeQuery = { nombre: 'scope', descripcion: 'Filtra por alcance.', schema: { type: 'string', enum: ['NUTRICION', 'ENTRENAMIENTO', 'ANTROPOMETRIA'] } };

/** Errores de una escritura REL/CON sobre un recurso que puede no ser revelable para el actor (09:213-233). */
const ESCRITURA_REVELABLE: Errores = {
  ...SESION,
  400: ['INVALID_REQUEST', 'UNKNOWN_FIELD'],
  404: ['RESOURCE_NOT_FOUND'],
};

const DEFINIDAS: readonly Operacion[] = [
  // ─── WP-02 ────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'API-ACC-01',
    metodo: 'post',
    ruta: '/registrations',
    resumen: 'Registrar identidad BE y perfil propio con A1 (términos) y A2 (privacidad) como actos separados. No concede A3.',
    autenticacion: 'PUBLIC',
    idempotencia: true,
    request: RegistrarIdentidadRequestSchema,
    exitos: [{ status: 201, schema: RegistrarIdentidadResponseSchema }],
    errores: {
      400: ['INVALID_REQUEST', 'UNKNOWN_FIELD'],
      409: ['REGISTRATION_NOT_AVAILABLE', 'IDEMPOTENCY_KEY_REUSED'],
      422: ['TERMS_VERSION_NOT_ACCEPTABLE', 'PRIVACY_VERSION_NOT_ACCEPTABLE'],
      429: ['RATE_LIMITED'],
    },
    fuente: '09v8:227-307',
  },
  {
    id: 'API-ACC-02',
    metodo: 'post',
    ruta: '/auth/sessions',
    resumen: 'Iniciar sesión local. Todo fallo de credenciales o de estado de cuenta responde el mismo 401 neutral.',
    autenticacion: 'PUBLIC',
    idempotencia: false,
    request: IniciarSesionRequestSchema,
    exitos: [{ status: 201, schema: IniciarSesionResponseSchema }],
    errores: { 400: ['INVALID_REQUEST', 'UNKNOWN_FIELD'], 401: ['INVALID_CREDENTIALS'], 429: ['RATE_LIMITED'] },
    fuente: '09v8:311-393',
  },
  {
    id: 'API-ACC-03',
    metodo: 'delete',
    ruta: '/auth/sessions/current',
    resumen: 'Finalizar la sesión actual. Idempotente: repetir responde 204.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 204 }],
    errores: { 400: ['INVALID_REQUEST'], 401: ['AUTHENTICATION_REQUIRED', 'SESSION_INVALID'] },
    fuente: '09v8:397-427 · DEUDA_LEGAJO DL-029 (idempotente: sesión ya no activa → 204)',
  },
  {
    id: 'API-ACC-04',
    metodo: 'delete',
    ruta: '/auth/sessions',
    resumen: 'Revocar todas las sesiones del titular.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 204 }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'] },
    fuente: '09v8:431-457',
  },
  {
    id: 'API-ACC-05',
    metodo: 'get',
    ruta: '/me',
    resumen: 'Identidad, estado operativo y sesión propios. `actorCapabilities` encauza superficies y no es PDP. No incluye A3.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: MeResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'] },
    fuente: '09v8:461-505',
  },
  {
    id: 'API-ACC-P1-03',
    metodo: 'post',
    ruta: '/me/account-closure-requests',
    resumen:
      'Cerrar la propia cuenta (P1, síncrono). Revoca sesiones, suprime el hash de la credencial, finaliza los vínculos por eventos y preserva la historia.',
    autenticacion: 'SESSION_STEP_UP',
    idempotencia: true,
    request: SolicitarCierreRequestSchema,
    exitos: [{ status: 201, schema: SolicitarCierreResponseSchema }],
    errores: {
      ...SESION,
      400: ['INVALID_REQUEST', 'UNKNOWN_FIELD'],
      403: ['STEP_UP_REQUIRED'],
      409: ['IDEMPOTENCY_KEY_REUSED'],
      422: ['VALIDATION_FAILED', 'INVALID_STATE_TRANSITION'],
    },
    fuente: '09v12:578-603 · DEUDA_LEGAJO DL-016/DL-017/DL-018',
  },
  {
    id: 'API-CON-05',
    metodo: 'get',
    ruta: '/me/health-data-consent-requirement',
    resumen: 'Requisito A3 y el último acto A3 del titular. `currentConsent: null` = A3 nunca otorgado.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: RequisitoDeConsentimientoDeSaludResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'] },
    fuente: '09:2379-2433',
  },
  // ─── WP-03 · REL (09v8 §6) ───────────────────────────────────────────────────────────────────
  {
    id: 'API-REL-01',
    metodo: 'post',
    ruta: '/relationship-requests',
    resumen:
      'Crear una solicitud de vínculo por alcance y finalidad. No concede acceso. Una equivalente pendiente se devuelve con 200 deduplicado (REG-06-44).',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: CrearSolicitudDeVinculoRequestSchema,
    exitos: [
      { status: 201, schema: CrearSolicitudDeVinculoResponseSchema },
      { status: 200, schema: SolicitudDeduplicadaResponseSchema },
    ],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['IDEMPOTENCY_KEY_REUSED', 'RESOURCE_CONFLICT'],
      422: ['PURPOSE_REQUIRED', 'SCOPE_NOT_AVAILABLE', 'COUNTERPART_NOT_ELIGIBLE', 'VALIDATION_FAILED'],
    },
    fuente: '09v8:1108-1192 · DEUDA_LEGAJO DL-035/DL-037',
  },
  {
    id: 'API-REL-02',
    metodo: 'get',
    ruta: '/me/relationship-requests',
    resumen: 'Solicitudes propias, enviadas y recibidas. No incluye información sanitaria.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [LIMIT, CURSOR, { nombre: 'state', descripcion: 'Estado de la solicitud (06 §7.3.1).', schema: { type: 'string', enum: ['PENDIENTE', 'ACEPTADA', 'RECHAZADA', 'CADUCADA', 'INVALIDADA'] } }],
    exitos: [{ status: 200, schema: ListaDeSolicitudesResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'] },
    fuente: '09v8:1196-1224',
  },
  {
    id: 'API-REL-03',
    metodo: 'post',
    ruta: '/relationship-requests/{requestId}/accept',
    resumen: 'Aceptar una solicitud (solo el asesorado titular). Crea el Vínculo por Alcance. No concede consentimiento.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: DecidirSolicitudRequestSchema,
    exitos: [{ status: 200, schema: AceptarSolicitudResponseSchema }],
    errores: { ...ESCRITURA_REVELABLE, 409: ['VERSION_CONFLICT', 'IDEMPOTENCY_KEY_REUSED'], 422: ['INVALID_STATE_TRANSITION'] },
    fuente: '09v8:1228-1290 · REG-06-49',
  },
  {
    id: 'API-REL-04',
    metodo: 'post',
    ruta: '/relationship-requests/{requestId}/reject',
    resumen: 'Rechazar una solicitud (solo el asesorado titular). La solicitud y su historia se conservan.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: DecidirSolicitudRequestSchema,
    exitos: [{ status: 200, schema: RechazarSolicitudResponseSchema }],
    errores: { ...ESCRITURA_REVELABLE, 409: ['VERSION_CONFLICT', 'IDEMPOTENCY_KEY_REUSED'], 422: ['INVALID_STATE_TRANSITION'] },
    fuente: '09v8:1294-1321 · DEUDA_LEGAJO DL-043',
  },
  {
    id: 'API-REL-05',
    metodo: 'get',
    ruta: '/me/relationships',
    resumen: 'Vínculos por alcance propios, con el modo de acceso calculado por el PDP (diagnóstico, no permiso).',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [LIMIT, CURSOR, { nombre: 'state', descripcion: 'Estado del vínculo por alcance (06 §7.5.1).', schema: { type: 'string', enum: ['ACEPTADO', 'PAUSADO', 'FINALIZADO'] } }, ALCANCE],
    exitos: [{ status: 200, schema: ListaDeVinculosResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'] },
    fuente: '09v8:1325-1369 · DEUDA_LEGAJO DL-034',
  },
  {
    id: 'API-REL-06',
    metodo: 'get',
    ruta: '/relationships/{relationshipId}',
    resumen: 'Detalle de un vínculo propio. No participante o inexistente → 404 idéntico.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: DetalleDeVinculoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v8:1373-1391 · DEUDA_LEGAJO DL-043',
  },
  {
    id: 'API-REL-07',
    metodo: 'post',
    ruta: '/relationships/{relationshipId}/pause',
    resumen: 'Pausar un vínculo por alcance, con motivo. El acceso profesional pasa a cero en la operación siguiente; no revoca B2.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: PausarVinculoRequestSchema,
    exitos: [{ status: 200, schema: VinculoResponseSchema }],
    errores: { ...ESCRITURA_REVELABLE, 409: ['VERSION_CONFLICT', 'IDEMPOTENCY_KEY_REUSED'], 422: ['INVALID_STATE_TRANSITION'] },
    fuente: '09v8:1395-1432 · DEUDA_LEGAJO DL-033',
  },
  {
    id: 'API-REL-08',
    metodo: 'post',
    ruta: '/relationships/{relationshipId}/resume',
    resumen: 'Reanudar un vínculo pausado (solo quien pausó). No restaura permisos: el PDP vuelve a evaluar todo.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: ReanudarVinculoRequestSchema,
    exitos: [{ status: 200, schema: VinculoResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      403: ['ACTION_FORBIDDEN'],
      409: ['VERSION_CONFLICT', 'IDEMPOTENCY_KEY_REUSED'],
      422: ['INVALID_STATE_TRANSITION'],
    },
    fuente: '09v8:1436-1468 · DEUDA_LEGAJO DL-033',
  },
  {
    id: 'API-REL-09',
    metodo: 'post',
    ruta: '/relationships/{relationshipId}/finalize',
    resumen: 'Finalizar un vínculo por alcance, con motivo. Terminal; sin lectura residual; conserva consentimientos como evidencia.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: FinalizarVinculoRequestSchema,
    exitos: [{ status: 200, schema: VinculoResponseSchema }],
    errores: { ...ESCRITURA_REVELABLE, 409: ['VERSION_CONFLICT', 'IDEMPOTENCY_KEY_REUSED'], 422: ['INVALID_STATE_TRANSITION'] },
    fuente: '09v8:1472-1494 · DEUDA_LEGAJO DL-033',
  },
  // ─── WP-03 · CON (09v8 §7; 09 §31-§37) ───────────────────────────────────────────────────────
  {
    id: 'API-CON-01',
    metodo: 'get',
    ruta: '/relationships/{relationshipId}/consent-requirements',
    resumen: 'Texto y versión de B2 aplicables a un vínculo propio (solo el asesorado titular).',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: RequisitosDeConsentimientoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v8:1500-1566 · DEUDA_LEGAJO DL-038/DL-039',
  },
  {
    id: 'API-CON-02',
    metodo: 'post',
    ruta: '/relationships/{relationshipId}/consents',
    resumen:
      'Otorgar B2 para la versión presentada (solo el asesorado titular). 201 al otorgar; 200 si ya estaba vigente con esa versión o al aceptar una versión nueva o reotorgar.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: OtorgarConsentimientoRequestSchema,
    exitos: [
      { status: 201, schema: ConsentimientoOtorgadoResponseSchema },
      { status: 200, schema: ConsentimientoOtorgadoResponseSchema },
    ],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['CONSENT_VERSION_STALE', 'IDEMPOTENCY_KEY_REUSED'],
      422: ['RELATIONSHIP_NOT_READY_FOR_CONSENT'],
    },
    fuente: '09v8:1570-1660 · DEUDA_LEGAJO DL-038',
  },
  {
    id: 'API-CON-03',
    metodo: 'get',
    ruta: '/me/consents',
    resumen: 'Consentimientos B2 propios como titular, con el modo de acceso calculado por el PDP.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [LIMIT, CURSOR, { nombre: 'state', descripcion: 'Estado de B2.', schema: { type: 'string', enum: ['ACTIVE', 'REVOKED'] } }, ALCANCE],
    exitos: [{ status: 200, schema: ListaDeConsentimientosResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'] },
    fuente: '09v8:1664-1695',
  },
  {
    id: 'API-CON-04',
    metodo: 'post',
    ruta: '/me/consents/{consentId}/revoke',
    resumen: 'Revocar B2. Idempotente por semántica (sin Idempotency-Key). Corta el acceso futuro; no finaliza el vínculo.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: ConsentimientoRevocadoResponseSchema }],
    errores: ESCRITURA_REVELABLE,
    fuente: '09v8:1699-1758',
  },
  {
    id: 'API-CON-06',
    metodo: 'post',
    ruta: '/me/health-data-consents',
    resumen: 'Otorgar o reotorgar A3 (un acto nuevo). No crea B2 ni habilita a ningún profesional.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: OtorgarConsentimientoDeSaludRequestSchema,
    exitos: [{ status: 201, schema: ConsentimientoDeSaludOtorgadoResponseSchema }],
    errores: {
      ...SESION,
      400: ['INVALID_REQUEST', 'UNKNOWN_FIELD'],
      409: ['CONSENT_VERSION_STALE', 'CONSENT_ALREADY_ACTIVE', 'IDEMPOTENCY_KEY_REUSED'],
      422: ['HEALTH_DATA_CONSENT_NOT_AVAILABLE'],
    },
    fuente: '09:2437-2519',
  },
  {
    id: 'API-CON-07',
    metodo: 'get',
    ruta: '/me/health-data-consents',
    resumen: 'Historial de actos A3 del titular. No mezcla B2 ni expone IP o user-agent.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [LIMIT, CURSOR],
    exitos: [{ status: 200, schema: HistorialDeConsentimientoDeSaludResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'] },
    fuente: '09:2523-2554',
  },
  {
    id: 'API-CON-08',
    metodo: 'post',
    ruta: '/me/health-data-consents/{consentId}/revoke',
    resumen: 'Revocar A3. Idempotente por semántica. El PDP bloquea de inmediato las operaciones sensibles, incluido el acceso profesional.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: ConsentimientoRevocadoResponseSchema }],
    errores: ESCRITURA_REVELABLE,
    fuente: '09:2558-2621 · 08:406 (paso 1) · DEUDA_LEGAJO DL-021',
  },
  // ─── WP-03 · DSH-03 mínimo (09v11 §15; DL-031) ───────────────────────────────────────────────
  {
    id: 'API-DSH-03',
    metodo: 'get',
    ruta: '/advisees/{adviseeId}/dashboard',
    resumen:
      'Dashboard del asesorado para un profesional, evaluado por el PDP en cada alcance. Cada alcance permitido trae el resumen factual de su dominio, o `null` si todavía no tiene datos. Ningún alcance autorizado → 404 idéntico a inexistente.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [
      { nombre: 'periodStart', descripcion: 'Inicio del período (RFC 3339).', schema: { type: 'string', format: 'date-time' } },
      { nombre: 'periodEnd', descripcion: 'Fin del período (RFC 3339).', schema: { type: 'string', format: 'date-time' } },
    ],
    exitos: [{ status: 200, schema: DashboardResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v11:895-950 · 08:581, 09:715 (SESSION con datos sintéticos) · DEUDA_LEGAJO DL-031',
  },
  // ─── WP-04 · NUT (09v9; CONS §11.2) e INT-NUT-01 (09v12) ─────────────────────────────────────
  {
    id: 'API-NUT-01',
    metodo: 'post',
    ruta: '/advisees/{adviseeId}/nutrition/evaluations',
    resumen: 'Registrar una evaluación nutricional. Cada dato declara su fuente (informado, observado o calculado). No sobrescribe evaluaciones anteriores.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: CrearEvaluacionRequestSchema,
    exitos: [{ status: 201, schema: CrearEvaluacionResponseSchema }],
    errores: { ...ESCRITURA_REVELABLE, 409: ['IDEMPOTENCY_KEY_REUSED'], 422: ['NUTRITION_EVALUATION_INVALID'] },
    fuente: '09v9:325-377 · DEUDA_LEGAJO DL-048, DL-055',
  },
  {
    id: 'API-NUT-02',
    metodo: 'get',
    ruta: '/advisees/{adviseeId}/nutrition/evaluations',
    resumen: 'Evaluaciones propias del profesional sobre el asesorado, paginadas.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [LIMIT, CURSOR],
    exitos: [{ status: 200, schema: ListaDeEvaluacionesResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v9:381-387 · DEUDA_LEGAJO DL-055, DL-057',
  },
  {
    id: 'API-NUT-03',
    metodo: 'get',
    ruta: '/nutrition/evaluations/{evaluationId}',
    resumen: 'Una evaluación. Inexistente, ajena o no autorizada → el mismo 404.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: EvaluacionResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v9:391-401',
  },
  {
    id: 'API-NUT-04',
    metodo: 'post',
    ruta: '/advisees/{adviseeId}/nutrition/objectives',
    resumen: 'Emitir una nueva versión de objetivo: decisión profesional con fundamento obligatorio. BE no calcula el requerimiento. La anterior se conserva.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: CrearObjetivoRequestSchema,
    exitos: [{ status: 201, schema: ObjetivoResponseSchema }],
    errores: { ...ESCRITURA_REVELABLE, 409: ['IDEMPOTENCY_KEY_REUSED'], 422: ['NUTRITION_OBJECTIVE_INVALID', 'EVALUATION_NOT_COMPATIBLE'] },
    fuente: '09v9:405-444 · REG-06-123 · INV-06-133',
  },
  {
    id: 'API-NUT-05',
    metodo: 'get',
    ruta: '/advisees/{adviseeId}/nutrition/objectives',
    resumen: 'Historia de versiones de objetivo, con la efectiva marcada por relación de sucesión.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [LIMIT, CURSOR],
    exitos: [{ status: 200, schema: ListaDeObjetivosResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v9:448-452',
  },
  {
    id: 'API-NUT-06',
    metodo: 'get',
    ruta: '/advisees/{adviseeId}/nutrition/objectives/effective',
    resumen: 'Objetivo efectivo: la versión terminal de la sucesión, nunca «la última por fecha». `objective: null` si no hay.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: ObjetivoEfectivoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v9:456-472 · INV-06-107',
  },
  {
    id: 'API-NUT-07',
    metodo: 'post',
    ruta: '/advisees/{adviseeId}/nutrition/plans',
    resumen:
      'Crear un borrador de plan: no vigente, no abre proceso ni ocupa capacidad. Con `basedOnPlanId`, borrador sucesor de la versión efectiva, sin tocarla (DL-047). Un solo borrador por plan.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: CrearPlanRequestSchema,
    exitos: [{ status: 201, schema: PlanResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['IDEMPOTENCY_KEY_REUSED', 'VERSION_CONFLICT'],
      422: ['OBJECTIVE_NOT_EFFECTIVE_OR_COMPATIBLE', 'NUTRITION_PLAN_STRUCTURE_INVALID', 'CATALOG_REFERENCE_INVALID', 'EXCHANGE_MODE_NOT_AVAILABLE', 'VALIDATION_FAILED'],
    },
    fuente: '09v9:476-499 · UC-P10 V07 · DEUDA_LEGAJO DL-046, DL-047, DL-055',
  },
  {
    id: 'API-NUT-08',
    metodo: 'get',
    ruta: '/advisees/{adviseeId}/nutrition/plans',
    resumen: 'Versiones del plan del profesional para el asesorado, sin la jerarquía.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [LIMIT, CURSOR, { nombre: 'state', descripcion: 'DRAFT o ACTIVATED.', schema: { type: 'string', enum: ['DRAFT', 'ACTIVATED'] } }],
    exitos: [{ status: 200, schema: ListaDePlanesResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v9:503-509',
  },
  {
    id: 'API-NUT-09',
    metodo: 'get',
    ruta: '/nutrition/plans/{planId}',
    resumen: 'Una versión de plan. Activada: se reconstruye desde la instantánea, nunca desde el catálogo vivo. El asesorado ve solo versiones activadas.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: PlanResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v9:513-519 · REG-06-105',
  },
  {
    id: 'API-NUT-10',
    metodo: 'patch',
    ruta: '/nutrition/plans/{planId}',
    resumen: 'Guardar un borrador (reemplaza la jerarquía). Una versión activada no se edita: 422 PLAN_NOT_EDITABLE (INV-06-109).',
    autenticacion: 'SESSION',
    idempotencia: false,
    request: EditarBorradorRequestSchema,
    exitos: [{ status: 200, schema: PlanResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['VERSION_CONFLICT'],
      422: ['PLAN_NOT_EDITABLE', 'NUTRITION_PLAN_STRUCTURE_INVALID', 'CATALOG_REFERENCE_INVALID', 'EXCHANGE_MODE_NOT_AVAILABLE', 'OBJECTIVE_NOT_EFFECTIVE_OR_COMPATIBLE'],
    },
    fuente: '09v9:523-562 · 06:4307',
  },
  {
    id: 'API-NUT-11',
    metodo: 'post',
    ruta: '/nutrition/plans/{planId}/validate',
    resumen: 'Validar un borrador sin activarlo. Responde 200 aunque haya problemas, con cada problema anclado a su ruta.',
    autenticacion: 'SESSION',
    idempotencia: false,
    request: VersionEsperadaRequestSchema,
    exitos: [{ status: 200, schema: ValidacionDePlanResponseSchema }],
    errores: { ...ESCRITURA_REVELABLE, 409: ['VERSION_CONFLICT'], 422: ['PLAN_NOT_EDITABLE'] },
    fuente: '09v9:566-597 · UC-I04',
  },
  {
    id: 'API-NUT-12',
    metodo: 'post',
    ruta: '/nutrition/plans/{planId}/activate',
    resumen:
      'Activar: en una transacción, PDP, validación, instantánea antes de la vigencia, vigencia única y Proceso nuevo (con capacidad) o continuidad. Si algo falla, no cambia nada.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: VersionEsperadaRequestSchema,
    exitos: [{ status: 200, schema: ActivacionDePlanResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['VERSION_CONFLICT', 'ACTIVE_PLAN_CONFLICT', 'IDEMPOTENCY_KEY_REUSED'],
      422: ['OPERATION_NOT_READY', 'CAPACITY_NOT_AVAILABLE'],
    },
    fuente: '09v9:601-644 · REG-06-104 · REG-06-91 · DEUDA_LEGAJO DL-051, DL-055 (NUTRITION_SCOPE_NOT_OPERATIONAL: 404)',
  },
  {
    id: 'API-NUT-13',
    metodo: 'get',
    ruta: '/nutrition/catalog-items',
    resumen: 'Catálogo nutricional BE: el sembrado (global) y el propio del profesional. Solo profesionales de Nutrición.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [LIMIT, CURSOR, { nombre: 'q', descripcion: 'Texto a buscar en el nombre.', schema: { type: 'string' } }, { nombre: 'type', descripcion: 'FOOD.', schema: { type: 'string', enum: ['FOOD'] } }],
    exitos: [{ status: 200, schema: ListaDeCatalogoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'], 403: ['ACTION_FORBIDDEN'] },
    fuente: '09v9:648-654 · REG-06-99, 135',
  },
  {
    id: 'API-INT-NUT-01',
    metodo: 'post',
    ruta: '/nutrition/catalog-items',
    resumen: 'Cargar manualmente un alimento al catálogo propio del profesional (fallback sin proveedor, RF-027).',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: CrearElementoDeCatalogoRequestSchema,
    exitos: [{ status: 201, schema: ElementoDeCatalogoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'UNKNOWN_FIELD'], 403: ['ACTION_FORBIDDEN'], 409: ['IDEMPOTENCY_KEY_REUSED'] },
    fuente: '09v12:111-160 · RF-027',
  },
  {
    id: 'API-INT-NUT-02',
    metodo: 'post',
    ruta: '/nutrition/catalog-import-candidates',
    resumen:
      'Consultar un alimento en Open Food Facts por su código de barras y crear un candidato de importación: todavía no es un elemento del catálogo. Proveedor caído → 503 con el catálogo propio y la carga manual disponibles.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: CrearCandidatoDeAlimentoRequestSchema,
    exitos: [{ status: 201, schema: CandidatoDeAlimentoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'UNKNOWN_FIELD'], 403: ['ACTION_FORBIDDEN'], 409: ['IDEMPOTENCY_KEY_REUSED'], 422: ['IMPORT_SOURCE_NOT_FOUND'], 503: ['DEPENDENCY_UNAVAILABLE'] },
    fuente: '09v12:166-236 · RF-028 · UC-I07 · UC-I08 · docs/paquetes/WP-08.md',
  },
  {
    id: 'API-INT-NUT-03',
    metodo: 'post',
    ruta: '/nutrition/catalog-import-candidates/{candidateId}/resolve',
    resumen:
      'Resolver un candidato propio: IMPORT lo incorpora al catálogo con procedencia CONTROLLED_IMPORT y los datos corregidos; REJECT no crea nada. Un candidato ajeno es 404; uno resuelto o vencido, 422.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: ResolverCandidatoDeAlimentoRequestSchema,
    exitos: [{ status: 200, schema: ResolucionDeAlimentoResponseSchema }],
    errores: {
      ...SESION,
      400: ['INVALID_REQUEST', 'UNKNOWN_FIELD'],
      403: ['ACTION_FORBIDDEN'],
      404: ['RESOURCE_NOT_FOUND'],
      409: ['IDEMPOTENCY_KEY_REUSED'],
      422: ['IMPORT_CANDIDATE_NOT_RESOLVABLE', 'REVIEWED_CONTENT_INVALID'],
    },
    fuente: '09v12:238-305 · RF-028 · RF-060 · UC-I07',
  },
  {
    id: 'API-NUT-14',
    metodo: 'get',
    ruta: '/me/nutrition/today',
    resumen: '«Hoy» del asesorado: la instantánea vigente y sus registros del día. Sin registros → NO_DATA, nunca 0 %. No elige un día tipo en silencio.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [{ nombre: 'dayTypeId', descripcion: 'Día tipo elegido por el asesorado (DL-049).', schema: { type: 'string' } }],
    exitos: [{ status: 200, schema: HoyResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'] },
    fuente: '09v9:658-680 · UC-P12 E06 · DEUDA_LEGAJO DL-049',
  },
  {
    id: 'API-NUT-15',
    metodo: 'post',
    ruta: '/me/nutrition/executions',
    resumen:
      'Registrar una ingesta: prescripta (comida y opción de la instantánea vigente, cantidades opcionales) o fuera del plan (texto libre). No modifica el plan. Un reintento no duplica.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: RegistrarIngestaRequestSchema,
    exitos: [
      { status: 201, schema: IngestaResponseSchema },
      { status: 200, schema: IngestaResponseSchema },
    ],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['IDEMPOTENCY_KEY_REUSED', 'EXECUTION_ALREADY_REGISTERED_INCOMPATIBLY'],
      422: ['ACTIVE_PLAN_REQUIRED', 'NUTRITION_EXECUTION_INVALID'],
    },
    fuente: '09v9:684-746 · CONS:564-628 · DEUDA_LEGAJO DL-049, DL-050',
  },
  {
    id: 'API-NUT-16-LISTA',
    metodo: 'get',
    ruta: '/me/nutrition/executions',
    resumen: 'Registros propios del asesorado (B10-05 NUT-11). Exige A3 vigente.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [LIMIT, CURSOR],
    exitos: [{ status: 200, schema: ListaDeIngestasResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'], 403: ['ACTION_FORBIDDEN'] },
    fuente: 'B10-05 NUT-11 · 10-B01:351-357 · 08:406 · DEUDA_LEGAJO DL-055',
  },
  {
    id: 'API-NUT-16',
    metodo: 'get',
    ruta: '/nutrition/executions/{executionId}',
    resumen: 'Una ingesta con su original, sus correcciones y la vista efectiva por relación de corrección.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: IngestaResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v9:750-756 · REG-06-16',
  },
  {
    id: 'API-NUT-17',
    metodo: 'get',
    ruta: '/advisees/{adviseeId}/nutrition/review-context',
    resumen: 'Contexto de revisión: objetivo, versiones del período, ingestas, contraste descriptivo, días sin dato y revisiones previas. Ver no es revisar.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [
      { nombre: 'periodStart', descripcion: 'Fecha local YYYY-MM-DD.', schema: { type: 'string', format: 'date' } },
      { nombre: 'periodEnd', descripcion: 'Fecha local YYYY-MM-DD.', schema: { type: 'string', format: 'date' } },
    ],
    exitos: [{ status: 200, schema: ContextoDeRevisionResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v9:793-837 · REG-06-125 · INV-06-135',
  },
  {
    id: 'API-NUT-18',
    metodo: 'post',
    ruta: '/advisees/{adviseeId}/nutrition/reviews',
    resumen: 'Registrar una revisión válida: evidencia reconstruible, interpretación, uno de los seis resultados, fundamento y próxima acción o cierre. No aplica nada.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: RegistrarRevisionRequestSchema,
    exitos: [{ status: 201, schema: RevisionResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['IDEMPOTENCY_KEY_REUSED'],
      422: ['REVIEW_EVIDENCE_NOT_RECONSTRUCTIBLE', 'REVIEW_COMPONENT_REQUIRED', 'REVIEW_RESULT_INVALID', 'REVIEW_NOT_ALLOWED'],
    },
    fuente: '09v9:842-900 · REG-06-141, 144 · UC-I05',
  },
  {
    id: 'API-NUT-19',
    metodo: 'get',
    ruta: '/nutrition/reviews/{reviewId}',
    resumen: 'Una revisión y, si se aplicó, el evento ContinuidadOCierreAplicado.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: RevisionResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v9:904-910',
  },
  {
    id: 'API-NUT-20',
    metodo: 'post',
    ruta: '/nutrition/reviews/{reviewId}/apply',
    resumen:
      'Aplicar la continuidad o el cierre (UC-I06): primero la consecuencia (borrador sucesor, objetivo nuevo, próxima revisión o cierre) y después el evento. Sin consecuencia aplicada no hay evento.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: VersionEsperadaRequestSchema,
    exitos: [{ status: 200, schema: AplicarRevisionResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['VERSION_CONFLICT', 'REVIEW_ALREADY_APPLIED', 'IDEMPOTENCY_KEY_REUSED'],
      422: ['CONTINUITY_ACTION_NOT_APPLICABLE', 'REVIEW_NOT_VALID_FOR_APPLICATION'],
    },
    fuente: '09v9:914-961 · REG-06-75, 77 · DEUDA_LEGAJO DL-052',
  },
  {
    id: 'API-NUT-21',
    metodo: 'post',
    ruta: '/nutrition/executions/{executionId}/corrections',
    resumen: 'Estructurar una ingesta libre como estimación profesional: Corrección trazable, el original queda intacto y la vista efectiva se resuelve por relación.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: CorregirIngestaRequestSchema,
    exitos: [{ status: 201, schema: IngestaResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['IDEMPOTENCY_KEY_REUSED'],
      422: ['NUTRITION_FREE_DESCRIPTION_REQUIRED', 'STRUCTURED_ESTIMATE_INVALID', 'CORRECTION_NOT_ALLOWED'],
    },
    fuente: 'CONS:632-685 · REG-06-14, 15, 16, 121',
  },
  // ─── ANT · antropometría (09v11; consolidado v0.16 §23 y §24) ─────────────────────────────────
  {
    id: 'API-ANT-01',
    metodo: 'get',
    ruta: '/anthropometry/specifications',
    resumen:
      'Especificaciones admitidas: protocolos y métodos con su versión vigente. Evita hardcodear contenido técnico en las superficies. El contenido es sintético de demostración y está rotulado como tal.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [
      LIMIT,
      CURSOR,
      { nombre: 'kind', descripcion: 'PROTOCOL o METHOD.', schema: { type: 'string', enum: ['PROTOCOL', 'METHOD'] } },
      {
        nombre: 'status',
        descripcion: 'CURRENT (por defecto) o HISTORICAL. Se deriva de la cadena de versiones: una versión con sucesora es histórica. Las históricas se consultan, no se seleccionan (REG-06-203).',
        schema: { type: 'string', enum: ['CURRENT', 'HISTORICAL'] },
      },
    ],
    exitos: [{ status: 200, schema: ListaDeEspecificacionesResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'], 403: ['ACTION_FORBIDDEN'] },
    fuente: '09v11:336-366 · REG-06-157 · WP-05 §0 D-C',
  },
  {
    id: 'API-ANT-02',
    metodo: 'post',
    ruta: '/advisees/{adviseeId}/anthropometry/evaluations',
    resumen:
      'Crear la evaluación antropométrica ya REGISTRADA, en un solo acto atómico: mediciones directas, cálculos pedidos, evento y registro en la misma transacción. Es la vía directa, distinta del borrador.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: CrearEvaluacionAntropometricaRequestSchema,
    exitos: [{ status: 201, schema: EvaluacionAntropometricaResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['IDEMPOTENCY_KEY_REUSED'],
      422: ['ANTHROPOMETRY_EVALUATION_INVALID', 'SPECIFICATION_REFERENCE_INVALID', 'METHOD_VERSION_NOT_SELECTABLE', 'CALCULATION_INPUTS_INSUFFICIENT', 'CALCULATION_NOT_REPRODUCIBLE'],
    },
    fuente: '09v11 §6 · 09v16:1704, 1709-1713 · REG-06-214',
  },
  {
    id: 'API-ANT-07',
    metodo: 'post',
    ruta: '/advisees/{adviseeId}/anthropometry/evaluation-drafts',
    resumen:
      'Crear la evaluación antropométrica EN PREPARACIÓN. El borrador no es historia: no alimenta la serie ni figura como última evaluación registrada.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: CrearBorradorRequestSchema,
    exitos: [{ status: 201, schema: EvaluacionAntropometricaResponseSchema }],
    errores: { ...ESCRITURA_REVELABLE, 409: ['IDEMPOTENCY_KEY_REUSED'], 422: ['ANTHROPOMETRY_EVALUATION_INVALID', 'SPECIFICATION_REFERENCE_INVALID'] },
    fuente: '09v16 §23.2 · REG-06-214/215',
  },
  {
    id: 'API-ANT-08',
    metodo: 'get',
    ruta: '/advisees/{adviseeId}/anthropometry/evaluation-drafts',
    resumen: 'Borradores retomables del profesional para ese asesorado. Un borrador de otro profesional no aparece.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [LIMIT, CURSOR],
    exitos: [{ status: 200, schema: ListaDeEvaluacionesAntropometricasResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v16 §23.3 · 08 §56.5',
  },
  {
    id: 'API-ANT-04',
    metodo: 'get',
    ruta: '/anthropometry/evaluations/{evaluationId}',
    resumen:
      'Consultar una evaluación REGISTRADA propia. No es una vía residual para leer un borrador: un borrador por esta ruta devuelve el mismo 404 que lo inexistente, igual que una evaluación ajena.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: EvaluacionAntropometricaResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v11 §8 · 09v16:1718, 2235 · 08 §56.5',
  },
  {
    id: 'API-ANT-09',
    metodo: 'get',
    ruta: '/anthropometry/evaluation-drafts/{evaluationId}',
    resumen:
      'Consultar el borrador propio, en la colección del borrador. Uno ajeno, exista o no, devuelve el mismo 404: no aparece ni como bloqueado ni como existente.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: EvaluacionAntropometricaResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v16 §23.4 · 08 §56.5 · DV-05 caso 10',
  },
  {
    id: 'API-ANT-10',
    metodo: 'put',
    ruta: '/anthropometry/evaluation-drafts/{evaluationId}',
    resumen:
      'Guardar el borrador. Reemplaza el contenido declarado y avanza el token de trabajo: el contenido de preparación no adquiere autoridad histórica por persistirse.',
    autenticacion: 'SESSION',
    idempotencia: false,
    request: GuardarBorradorRequestSchema,
    exitos: [{ status: 200, schema: EvaluacionAntropometricaResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['VERSION_CONFLICT'],
      422: ['ANTHROPOMETRY_EVALUATION_NOT_EDITABLE', 'SPECIFICATION_REFERENCE_INVALID'],
    },
    fuente: '09v16 §23.5 · REG-06-215/216',
  },
  {
    id: 'API-ANT-11',
    metodo: 'post',
    ruta: '/anthropometry/evaluation-drafts/{evaluationId}/register',
    resumen:
      'Registrar la evaluación: el acto explícito que la vuelve historia. Exige contenido registrable. REGISTRADA es terminal: los cambios posteriores usan corrección o anulación.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: RegistrarEvaluacionRequestSchema,
    exitos: [{ status: 200, schema: EvaluacionAntropometricaResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['VERSION_CONFLICT', 'IDEMPOTENCY_KEY_REUSED'],
      422: ['ANTHROPOMETRY_EVALUATION_INVALID', 'ANTHROPOMETRY_EVALUATION_NOT_EDITABLE'],
    },
    fuente: '09v16 §23.6 · REG-06-214 incisos 4 y 5',
  },
  {
    id: 'API-ANT-03',
    metodo: 'get',
    ruta: '/advisees/{adviseeId}/anthropometry/evaluations',
    resumen: 'Listar las evaluaciones REGISTRADAS del asesorado. Los borradores no aparecen acá: no son historia.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [LIMIT, CURSOR],
    exitos: [{ status: 200, schema: ListaDeEvaluacionesAntropometricasResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v16 §23.1 · REG-06-215',
  },
  {
    id: 'API-ANT-05',
    metodo: 'post',
    ruta: '/anthropometry/evaluations/{evaluationId}/corrections',
    resumen:
      'Corregir una medición con trazabilidad: el original y la cadena se conservan, y la vista efectiva se resuelve por relación, nunca por la fecha más reciente. Los derivados afectados se reemiten sin sobrescribir los anteriores.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: CorregirMedicionRequestSchema,
    exitos: [{ status: 201, schema: z.strictObject({ data: MedicionSchema.loose() }) }],
    errores: { ...ESCRITURA_REVELABLE, 409: ['IDEMPOTENCY_KEY_REUSED', 'RESOURCE_CONFLICT'], 422: ['CORRECTION_NOT_ALLOWED', 'UNIT_NOT_COMPATIBLE'] },
    fuente: '09v11:579-657 · REG-06-160/161/219 · UC-I12',
  },
  {
    id: 'API-ANT-12',
    metodo: 'post',
    ruta: '/anthropometry/measurements/{measurementId}/annulments',
    resumen:
      'Anular una medición: evento aditivo y terminal, que no borra el original. Una segunda anulación de la misma medición responde 200 con la anulación existente y alreadyAnnulled: no produce un segundo efecto ni un error nuevo. No existe reversión.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: AnularMedicionRequestSchema,
    exitos: [
      { status: 201, schema: AnularMedicionResponseSchema },
      { status: 200, schema: AnularMedicionResponseSchema },
    ],
    errores: { ...ESCRITURA_REVELABLE, 409: ['IDEMPOTENCY_KEY_REUSED', 'VERSION_CONFLICT'], 422: ['ANTHROPOMETRY_ANNULMENT_NOT_ALLOWED'] },
    fuente: '09v16 §24.1 · REG-06-217/218/219/220 · DV-05 caso 6 · DEUDA_LEGAJO DL-059',
  },
  {
    id: 'API-ANT-06',
    metodo: 'get',
    ruta: '/advisees/{adviseeId}/anthropometry/progress',
    resumen:
      'Evolución antropométrica del asesorado. Un checkpoint sin medición vigente es NO_DATA y no lleva valor: no se interpola, no se imputa y no se arrastra. Un cero medido sigue siendo un punto disponible.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [
      { nombre: 'periodStart', descripcion: 'Primer día del período (fecha local).', schema: { type: 'string', format: 'date' } },
      { nombre: 'periodEnd', descripcion: 'Último día del período (fecha local).', schema: { type: 'string', format: 'date' } },
      { nombre: 'metric', descripcion: 'Métricas separadas por coma. Sin esto, todas las que tengan dato.', schema: { type: 'string' } },
    ],
    exitos: [{ status: 200, schema: EvolucionResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v11:710-760 · REG-06-165/166/167 · INV-06-176/177 · DV-05 caso 7',
  },
  {
    id: 'API-ANT-06-PROPIA',
    metodo: 'get',
    ruta: '/me/anthropometry/progress',
    resumen: 'La misma evolución, del lado del asesorado, que RF-049 nombra como actor. La consume la APK.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [
      { nombre: 'periodStart', descripcion: 'Primer día del período (fecha local).', schema: { type: 'string', format: 'date' } },
      { nombre: 'periodEnd', descripcion: 'Último día del período (fecha local).', schema: { type: 'string', format: 'date' } },
      { nombre: 'metric', descripcion: 'Métricas separadas por coma. Sin esto, todas las que tengan dato.', schema: { type: 'string' } },
    ],
    exitos: [{ status: 200, schema: EvolucionResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'] },
    fuente: '04:583 (RF-049) · UC-P31 V03 · 04:1093',
  },
  // ─── MTH y CAL · el patrón transversal de cálculo reproducible (09v16 §21; T-06-N12) ─────────
  {
    id: 'API-MTH-01',
    metodo: 'get',
    ruta: '/professional-methods',
    resumen:
      'Métodos profesionales seleccionables, con su versión vigente, entradas requeridas, procedencias admisibles, unidad de salida y precisión declarada. Son metadatos: no acepta adviseeId y no implica compatibilidad con los datos de ninguna persona.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [LIMIT, CURSOR, { nombre: 'purpose', descripcion: 'Finalidad declarada del cálculo.', schema: { type: 'string', enum: ['ANTHROPOMETRIC_SUPPORT', 'NUTRITION_OBJECTIVE_SUPPORT'] } }],
    exitos: [{ status: 200, schema: ListaDeMetodosResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'], 403: ['ACTION_FORBIDDEN'] },
    fuente: '09v16 §21.1 · REG-06-203 · REG-06-204',
  },
  {
    id: 'API-MTH-02',
    metodo: 'get',
    ruta: '/professional-methods/{methodId}/versions/{versionId}',
    resumen:
      'La versión exacta de un método, seleccionable o histórica. Una versión histórica se consulta —las corridas la citan y tienen que poder explicarse— pero no se presenta como seleccionable. No devuelve datos de ningún asesorado.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: MetodoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 403: ['ACTION_FORBIDDEN'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v16 §21.2 · REG-06-203',
  },
  {
    id: 'API-CAL-01',
    metodo: 'post',
    ruta: '/advisees/{adviseeId}/calculations',
    resumen:
      'Ejecutar un método sobre entradas efectivas declaradas una por una. Disponible no es admisible: la versión declara qué entradas necesita, en qué unidades y de qué procedencias. La respuesta no afirma que se haya creado un objetivo, una prescripción ni un plan: no los crea.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: EjecutarCalculoRequestSchema,
    exitos: [{ status: 201, schema: CorridaResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['IDEMPOTENCY_KEY_REUSED'],
      422: ['METHOD_VERSION_NOT_SELECTABLE', 'CALCULATION_INPUTS_INSUFFICIENT', 'CALCULATION_NOT_REPRODUCIBLE'],
    },
    fuente: '09v16 §21.3 · REG-06-204/205 · TEST-CAL-002/003/007',
  },
  {
    id: 'API-CAL-02',
    metodo: 'get',
    ruta: '/advisees/{adviseeId}/calculations',
    resumen:
      'Las corridas revelables del asesorado. Coexisten: no se promedian, no se ordenan por «mejor» y ninguna se marca ganadora. La que el profesional adoptó viene con referenceForPurpose.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [LIMIT, CURSOR, { nombre: 'purpose', descripcion: 'Finalidad declarada del cálculo.', schema: { type: 'string', enum: ['ANTHROPOMETRIC_SUPPORT', 'NUTRITION_OBJECTIVE_SUPPORT'] } }],
    exitos: [{ status: 200, schema: ListaDeCorridasResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v16 §21.4 · REG-06-205 · TEST-CAL-004/005',
  },
  {
    id: 'API-CAL-03',
    metodo: 'get',
    ruta: '/calculations/{runId}',
    resumen:
      'Una corrida, con la versión exacta del método que se usó, la regla aplicada, la precisión declarada y la procedencia de cada entrada. Una corrida no revelable devuelve el mismo 404 que una inexistente.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: CorridaResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v16 §21.5 · REG-06-156 · REG-06-203 · TEST-CAL-001',
  },
  {
    id: 'API-CAL-04',
    metodo: 'put',
    ruta: '/advisees/{adviseeId}/calculation-references/{purpose}',
    resumen:
      'Adoptar una corrida como referencia profesional para una finalidad. Es una relación, no una mutación: no modifica la corrida, no borra las otras y no crea objetivo ni prescripción. Reemplazarla crea historia; adoptar la que ya es referencia responde 200 sin crear una relación nueva.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: AdoptarReferenciaRequestSchema,
    exitos: [
      { status: 201, schema: ReferenciaResponseSchema },
      { status: 200, schema: ReferenciaResponseSchema },
    ],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['IDEMPOTENCY_KEY_REUSED', 'VERSION_CONFLICT'],
      422: ['CALCULATION_REFERENCE_NOT_COMPATIBLE'],
    },
    fuente: '09v16 §21.6 · REG-06-207 · TEST-CAL-006',
  },
  // ─── WP-06 · TRN (09v10), INT-TRN-01 (09v12) y la lectura por período (DL-078) ─────────────────
  {
    id: 'API-TRN-01',
    metodo: 'post',
    ruta: '/advisees/{adviseeId}/training/evaluations',
    resumen: 'Registrar una evaluación de entrenamiento. Cada dato declara su fuente. Evidencia no es ejecución, y una evaluación posterior no sobrescribe la anterior.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: CrearEvaluacionDeEntrenamientoRequestSchema,
    exitos: [{ status: 201, schema: CrearEvaluacionResponseSchema }],
    errores: { ...ESCRITURA_REVELABLE, 409: ['IDEMPOTENCY_KEY_REUSED'], 422: ['TRAINING_EVALUATION_INVALID'] },
    fuente: '09v10:520-570 · REG-06-97 · DEUDA_LEGAJO DL-048, DL-080',
  },
  {
    id: 'API-TRN-02',
    metodo: 'get',
    ruta: '/advisees/{adviseeId}/training/evaluations',
    resumen: 'Evaluaciones de entrenamiento propias del profesional sobre el asesorado, paginadas.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [LIMIT, CURSOR],
    exitos: [{ status: 200, schema: ListaDeEvaluacionesDeEntrenamientoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v10:574-580 · CONS v0.16.1:189',
  },
  {
    id: 'API-TRN-03',
    metodo: 'get',
    ruta: '/training/evaluations/{evaluationId}',
    resumen: 'Una evaluación de entrenamiento. Inexistente, ajena o no autorizada → el mismo 404.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: EvaluacionDeEntrenamientoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v10:584-594',
  },
  {
    id: 'API-TRN-04',
    metodo: 'post',
    ruta: '/advisees/{adviseeId}/training/objectives',
    resumen: 'Emitir una nueva versión de objetivo de entrenamiento: decisión profesional con fundamento. La anterior se conserva; nunca se sobrescribe.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: CrearObjetivoDeEntrenamientoRequestSchema,
    exitos: [{ status: 201, schema: ObjetivoDeEntrenamientoResponseSchema }],
    errores: { ...ESCRITURA_REVELABLE, 409: ['IDEMPOTENCY_KEY_REUSED'], 422: ['TRAINING_OBJECTIVE_INVALID', 'EVALUATION_NOT_COMPATIBLE'] },
    fuente: '09v10:598-628 · REG-06-98',
  },
  {
    id: 'API-TRN-05',
    metodo: 'get',
    ruta: '/advisees/{adviseeId}/training/objectives',
    resumen: 'Historia de versiones de objetivo de entrenamiento, con la efectiva marcada por relación de sucesión.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [LIMIT, CURSOR],
    exitos: [{ status: 200, schema: ListaDeObjetivosDeEntrenamientoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v10:632-638',
  },
  {
    id: 'API-TRN-06',
    metodo: 'get',
    ruta: '/advisees/{adviseeId}/training/objectives/effective',
    resumen: 'Objetivo de entrenamiento efectivo: la terminal de la sucesión, nunca por timestamp. `objective: null` si no hay.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: ObjetivoDeEntrenamientoEfectivoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v10:642-658 · INV-06-107',
  },
  {
    id: 'API-TRN-07',
    metodo: 'post',
    ruta: '/advisees/{adviseeId}/training/plans',
    resumen:
      'Crear un borrador de plan de entrenamiento: estado DRAFT, no vigente, no abre proceso ni ocupa capacidad. El borrador es el mismo recurso del plan: no existe una colección de borradores de plan.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: CrearPlanDeEntrenamientoRequestSchema,
    exitos: [{ status: 201, schema: PlanDeEntrenamientoResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['IDEMPOTENCY_KEY_REUSED', 'VERSION_CONFLICT'],
      422: ['OBJECTIVE_NOT_EFFECTIVE_OR_COMPATIBLE', 'TRAINING_PLAN_STRUCTURE_INVALID', 'EXERCISE_REFERENCE_INVALID', 'INTENSITY_CRITERION_INVALID', 'VALIDATION_FAILED'],
    },
    fuente: '09v10:662-686 · REG-06-102 · DEUDA_LEGAJO DL-046, DL-047, DL-088',
  },
  {
    id: 'API-TRN-08',
    metodo: 'get',
    ruta: '/advisees/{adviseeId}/training/plans',
    resumen: 'Versiones del plan de entrenamiento, sin la jerarquía. `state` filtra DRAFT o ACTIVATED.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [LIMIT, CURSOR, { nombre: 'state', descripcion: 'Estado de la versión.', schema: { type: 'string', enum: ['DRAFT', 'ACTIVATED'] } }],
    exitos: [{ status: 200, schema: ListaDePlanesDeEntrenamientoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v10:690-696',
  },
  {
    id: 'API-TRN-09',
    metodo: 'get',
    ruta: '/training/plans/{planId}',
    resumen: 'Una versión de plan con su jerarquía. Si está activada, se reconstruye desde la instantánea, no desde el catálogo actual.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: PlanDeEntrenamientoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v10:700-706 · REG-06-112',
  },
  {
    id: 'API-TRN-10',
    metodo: 'patch',
    ruta: '/training/plans/{planId}',
    resumen:
      'Editar un borrador: bloque, microciclo opcional, sesión y prescripción. Valida la forma, no la calidad del programa: ni volumen, ni frecuencia, ni selección de ejercicios, ni progresión.',
    autenticacion: 'SESSION',
    idempotencia: false,
    request: EditarPlanDeEntrenamientoRequestSchema,
    exitos: [{ status: 200, schema: PlanDeEntrenamientoResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['VERSION_CONFLICT'],
      422: ['PLAN_NOT_EDITABLE', 'TRAINING_PLAN_STRUCTURE_INVALID', 'EXERCISE_REFERENCE_INVALID', 'INTENSITY_CRITERION_INVALID', 'OBJECTIVE_NOT_EFFECTIVE_OR_COMPATIBLE'],
    },
    fuente: '09v10:710-754 · REG-06-111, 126, 127, 128, 129',
  },
  {
    id: 'API-TRN-11',
    metodo: 'post',
    ruta: '/training/plans/{planId}/validate',
    resumen: 'Validar un borrador sin activarlo. 200 aunque `valid` sea falso: los problemas vienen vinculados a bloque, sesión y ejercicio. Validar no es un estado.',
    autenticacion: 'SESSION',
    idempotencia: false,
    request: VersionEsperadaRequestSchema,
    exitos: [{ status: 200, schema: ValidacionDePlanResponseSchema }],
    errores: { ...ESCRITURA_REVELABLE, 409: ['VERSION_CONFLICT'], 422: ['PLAN_NOT_EDITABLE'] },
    fuente: '09v10:758-784 · 06:4330 (no existe VALIDADO)',
  },
  {
    id: 'API-TRN-12',
    metodo: 'post',
    ruta: '/training/plans/{planId}/activate',
    resumen:
      'Activar: en una transacción, versión esperada, PDP, capacidad, validación, instantánea inmutable, cambio de versión efectiva y apertura del Proceso si es nuevo. La anterior se conserva.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: VersionEsperadaRequestSchema,
    exitos: [{ status: 200, schema: ActivacionDePlanDeEntrenamientoResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['VERSION_CONFLICT', 'ACTIVE_PLAN_CONFLICT', 'IDEMPOTENCY_KEY_REUSED'],
      422: ['OPERATION_NOT_READY', 'CAPACITY_NOT_AVAILABLE', 'PLAN_NOT_EDITABLE'],
    },
    fuente: '09v10:788-834 · REG-06-104, 105 · 06:5164 · DEUDA_LEGAJO DL-087',
  },
  {
    id: 'API-TRN-13',
    metodo: 'get',
    ruta: '/training/exercises',
    resumen: 'Catálogo propio de ejercicios, con procedencia. Sin porcentajes de músculo trabajado ni cálculos de volumen. Las zonas y el material didáctico llegan en WP-07.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [LIMIT, CURSOR, { nombre: 'q', descripcion: 'Texto a buscar en el nombre.', schema: { type: 'string', maxLength: 80 } }],
    exitos: [{ status: 200, schema: ListaDeEjerciciosResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'], 403: ['ACTION_FORBIDDEN'] },
    fuente: '09v10:838-854 · RF-037 · INV-06-143',
  },
  {
    id: 'API-INT-TRN-01',
    metodo: 'post',
    ruta: '/training/exercises',
    resumen: 'Cargar un ejercicio manualmente en el catálogo propio. Cero zonas es legítimo; no altera instantáneas activas.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: CrearEjercicioRequestSchema,
    exitos: [{ status: 201, schema: EjercicioDeCatalogoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'UNKNOWN_FIELD'], 403: ['ACTION_FORBIDDEN'], 409: ['IDEMPOTENCY_KEY_REUSED'], 422: ['VALIDATION_FAILED'] },
    fuente: '09v12:308-340 · RF-037 · REG-06-139 · docs/paquetes/WP-06.md §9.8',
  },
  {
    id: 'API-INT-TRN-02',
    metodo: 'post',
    ruta: '/training/catalog-import-candidates',
    resumen:
      'Consultar un ejercicio en wger por su número y crear un candidato de importación. Los músculos que declara wger son dato del proveedor: nunca se copian como zona BE. Proveedor caído → 503.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: CrearCandidatoDeEjercicioRequestSchema,
    exitos: [{ status: 201, schema: CandidatoDeEjercicioResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'UNKNOWN_FIELD'], 403: ['ACTION_FORBIDDEN'], 409: ['IDEMPOTENCY_KEY_REUSED'], 422: ['IMPORT_SOURCE_NOT_FOUND'], 503: ['DEPENDENCY_UNAVAILABLE'] },
    fuente: '09v12:349-381 · RF-038 · UC-I07 · UC-I08 · docs/paquetes/WP-08.md',
  },
  {
    id: 'API-INT-TRN-03',
    metodo: 'post',
    ruta: '/training/catalog-import-candidates/{candidateId}/resolve',
    resumen:
      'Resolver un candidato propio de wger: IMPORT crea el ejercicio con procedencia CONTROLLED_IMPORT y sin zonas BE; REJECT no crea nada. Un candidato ajeno es 404; uno resuelto o vencido, 422.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: ResolverCandidatoDeEjercicioRequestSchema,
    exitos: [{ status: 200, schema: ResolucionDeEjercicioResponseSchema }],
    errores: {
      ...SESION,
      400: ['INVALID_REQUEST', 'UNKNOWN_FIELD'],
      403: ['ACTION_FORBIDDEN'],
      404: ['RESOURCE_NOT_FOUND'],
      409: ['IDEMPOTENCY_KEY_REUSED'],
      422: ['IMPORT_CANDIDATE_NOT_RESOLVABLE', 'REVIEWED_CONTENT_INVALID'],
    },
    fuente: '09v12:383-411 · RF-038 · RF-060 · UC-I07',
  },
  {
    id: 'API-TRN-14',
    metodo: 'get',
    ruta: '/me/training/today',
    resumen: '«Hoy» del asesorado: las sesiones de la instantánea vigente como ocurrencias del día, con el estado de su registro. La ausencia de registro no se convierte en NOT_COMPLETED.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: HoyDeEntrenamientoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'] },
    fuente: '09v10:858-915 · H-09-TRN-01 · DEUDA_LEGAJO DL-077, DL-079',
  },
  {
    id: 'API-TRN-14-PERIODO',
    metodo: 'get',
    ruta: '/me/training/occurrences',
    resumen:
      'Ocurrencias de un período pasado, para registrar en diferido. Sin esta lectura, la sesión de anteayer no se podría registrar y la ausencia de registro se volvería permanente. Hasta 31 días, nunca después de hoy.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [
      { nombre: 'periodStart', descripcion: 'Fecha local YYYY-MM-DD.', schema: { type: 'string', format: 'date' }, obligatorio: true },
      { nombre: 'periodEnd', descripcion: 'Fecha local YYYY-MM-DD, no posterior a hoy. Hasta 31 días desde periodStart: es el tope de la lectura, que por eso no pagina (DL-078).', schema: { type: 'string', format: 'date' }, obligatorio: true },
    ],
    exitos: [{ status: 200, schema: OcurrenciasDelPeriodoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'] },
    fuente: 'DEUDA_LEGAJO DL-078 (diferencia con el 09, decidida por Dirección) · 09v10:188-189, 915',
  },
  {
    id: 'API-TRN-19-LISTA',
    metodo: 'get',
    ruta: '/me/training/executions',
    resumen:
      '«Tu historial»: las sesiones registradas propias por período. Exige A3 vigente; no depende de un plan vigente ni del acceso del profesional (DL-096). Hasta 31 días, nunca después de hoy.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [
      { nombre: 'periodStart', descripcion: 'Fecha local YYYY-MM-DD.', schema: { type: 'string', format: 'date' }, obligatorio: true },
      { nombre: 'periodEnd', descripcion: 'Fecha local YYYY-MM-DD, no posterior a hoy. Hasta 31 días desde periodStart: es el tope de la lectura, que por eso no pagina.', schema: { type: 'string', format: 'date' }, obligatorio: true },
    ],
    exitos: [{ status: 200, schema: HistorialDeEntrenamientoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 403: ['ACTION_FORBIDDEN'] },
    fuente: 'DEUDA_LEGAJO DL-096 (opción A, decidida por Dirección) · 08:199, 08:58, 08:406 · DL-089',
  },
  {
    id: 'API-TRN-15',
    metodo: 'put',
    ruta: '/training/occurrences/{occurrenceId}/execution-draft',
    resumen: 'Crear u obtener el borrador singular de una ocurrencia: 201 si lo creó, 200 si ya existía. Tocar «Comenzar» dos veces da el mismo borrador.',
    autenticacion: 'SESSION',
    idempotencia: false,
    request: AbrirBorradorDeEjecucionRequestSchema,
    requestOpcional: true,
    exitos: [
      { status: 201, schema: BorradorDeEjecucionResponseSchema },
      { status: 200, schema: BorradorDeEjecucionResponseSchema },
    ],
    errores: { ...ESCRITURA_REVELABLE, 422: ['ACTIVE_PLAN_REQUIRED', 'OCCURRENCE_NOT_EXECUTABLE'] },
    fuente: '09v10:919-965 · CAND-09-TRN-E · S10-TRN-01',
  },
  {
    id: 'API-TRN-16',
    metodo: 'get',
    ruta: '/training/execution-drafts/{draftId}',
    resumen: 'Un borrador de ejecución, solo para su titular. Un borrador no es evidencia ni ejecución registrada.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: BorradorDeEjecucionResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v10:969-982',
  },
  {
    id: 'API-TRN-17',
    metodo: 'patch',
    ruta: '/training/execution-drafts/{draftId}',
    resumen:
      'Guardar el borrador de forma incremental: granularidad, condición, motivo opcional, ejercicios por serie o resumidos, sustitución. No infiere lo faltante ni sintetiza series.',
    autenticacion: 'SESSION',
    idempotencia: false,
    request: EditarBorradorDeEjecucionRequestSchema,
    exitos: [{ status: 200, schema: BorradorDeEjecucionResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['VERSION_CONFLICT'],
      422: ['INVALID_STATE_TRANSITION', 'EXECUTION_GRANULARITY_INVALID', 'SESSION_CONDITION_INVALID', 'EXECUTION_VALUE_INVALID', 'EXERCISE_REFERENCE_INVALID'],
    },
    fuente: '09v10:986-1131 · REG-06-130, 131, 132 · INV-06-152',
  },
  {
    id: 'API-TRN-18',
    metodo: 'post',
    ruta: '/training/execution-drafts/{draftId}/confirm',
    resumen:
      'Confirmar la sesión: crea la ejecución registrada, inmutable, como recurso nuevo. Una sola por ocurrencia; un reintento no duplica. No existe la vuelta a borrador.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: VersionEsperadaRequestSchema,
    exitos: [{ status: 201, schema: ConfirmacionDeEjecucionResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['VERSION_CONFLICT', 'EXECUTION_ALREADY_REGISTERED', 'IDEMPOTENCY_KEY_REUSED'],
      422: ['EXECUTION_DRAFT_NOT_READY', 'INVALID_STATE_TRANSITION', 'ACTIVE_PLAN_REQUIRED'],
    },
    fuente: '09v10:1136-1193 · REG-06-115 · 06:5221',
  },
  {
    id: 'API-TRN-19',
    metodo: 'get',
    ruta: '/training/executions/{executionId}',
    resumen: 'Una ejecución registrada: la sesión planificada de la instantánea, el registro original, la cadena de correcciones y la vista efectiva por relación.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: EjecucionDeEntrenamientoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v10:1197-1217 · REG-06-16, 113',
  },
  {
    id: 'API-TRN-20',
    metodo: 'post',
    ruta: '/training/executions/{executionId}/corrections',
    resumen: 'Corregir una ejecución registrada: el original queda intacto, la corrección conserva autor y motivo, y la prescripción no se toca.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: CorregirEjecucionRequestSchema,
    exitos: [{ status: 201, schema: EjecucionDeEntrenamientoResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['IDEMPOTENCY_KEY_REUSED'],
      422: ['EXECUTION_GRANULARITY_INVALID', 'SESSION_CONDITION_INVALID', 'EXECUTION_VALUE_INVALID', 'EXERCISE_REFERENCE_INVALID', 'CORRECTION_NOT_ALLOWED'],
    },
    fuente: '09v10:1221-1257 · REG-06-116 · UC-E02 · DEUDA_LEGAJO DL-076',
  },
  {
    id: 'API-TRN-21',
    metodo: 'get',
    ruta: '/advisees/{adviseeId}/training/review-context',
    resumen: 'Contexto de revisión: objetivo, versiones, ejecuciones registradas, correcciones, días sin dato y revisiones previas. No calcula volumen, marcas, mapa ni puntaje. Ver no es revisar.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [
      { nombre: 'periodStart', descripcion: 'Fecha local YYYY-MM-DD.', schema: { type: 'string', format: 'date' } },
      { nombre: 'periodEnd', descripcion: 'Fecha local YYYY-MM-DD.', schema: { type: 'string', format: 'date' } },
    ],
    exitos: [{ status: 200, schema: ContextoDeRevisionDeEntrenamientoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v10:1261-1295 · 09v10 §40',
  },
  {
    id: 'API-TRN-22',
    metodo: 'post',
    ruta: '/advisees/{adviseeId}/training/reviews',
    resumen: 'Registrar una revisión de entrenamiento: uno de los seis resultados. La progresión se expresa como ADJUST o REPLACE; no existe un séptimo. No aplica nada.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: RegistrarRevisionDeEntrenamientoRequestSchema,
    exitos: [{ status: 201, schema: RevisionDeEntrenamientoResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['IDEMPOTENCY_KEY_REUSED'],
      422: ['REVIEW_EVIDENCE_NOT_RECONSTRUCTIBLE', 'REVIEW_COMPONENT_REQUIRED', 'REVIEW_RESULT_INVALID', 'REVIEW_NOT_ALLOWED'],
    },
    fuente: '09v10:1299-1371 · REG-06-117, 141 · INV-06-126',
  },
  {
    id: 'API-TRN-23',
    metodo: 'get',
    ruta: '/training/reviews/{reviewId}',
    resumen: 'Una revisión de entrenamiento y, si se aplicó, el evento ContinuidadOCierreAplicado.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: RevisionDeEntrenamientoResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v10:1375-1381',
  },
  {
    id: 'API-TRN-24',
    metodo: 'post',
    ruta: '/training/reviews/{reviewId}/apply',
    resumen: 'Aplicar la continuidad o el cierre: primero la consecuencia (borrador sucesor, objetivo nuevo, próxima revisión o cierre) y después el evento. Sin éxito completo no hay evento.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: VersionEsperadaRequestSchema,
    exitos: [{ status: 200, schema: AplicarRevisionResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['VERSION_CONFLICT', 'REVIEW_ALREADY_APPLIED', 'IDEMPOTENCY_KEY_REUSED'],
      422: ['CONTINUITY_ACTION_NOT_APPLICABLE', 'REVIEW_NOT_VALID_FOR_APPLICATION'],
    },
    fuente: '09v10:1385-1442 · REG-06-75, 77',
  },
  // ─── WP-07 · FRM (09v16.1 §22). Información profesional pertinente (RF-071) ─────────────────────
  {
    id: 'API-FRM-01',
    metodo: 'get',
    ruta: '/form-templates',
    resumen: 'Catálogo BE de plantillas, sintético y de demostración. Metadatos: una plantilla listada no prueba que todos sus campos puedan solicitarse a un asesorado concreto.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [
      LIMIT,
      CURSOR,
      { nombre: 'domain', descripcion: 'Filtra por el Alcance de la plantilla, si está clasificada.', schema: { type: 'string', enum: ['NUTRICION', 'ENTRENAMIENTO', 'ANTROPOMETRIA'] } },
      { nombre: 'purpose', descripcion: 'Filtra por texto libre de la descripción de la plantilla.', schema: { type: 'string' } },
      { nombre: 'status', descripcion: 'Filtra por seleccionabilidad.', schema: { type: 'string', enum: ['SELECTABLE', 'HISTORICAL_NOT_SELECTABLE'] } },
    ],
    exitos: [{ status: 200, schema: ListaDePlantillasResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'] },
    fuente: '09v16.1 §22.1 · REG-06-209',
  },
  {
    id: 'API-FRM-02',
    metodo: 'get',
    ruta: '/form-templates/{templateId}/versions/{versionId}',
    resumen: 'La versión exacta de una plantilla: secciones, campos, tipos/unidades, categoría de cada campo, requerido/opcional y estado. No devuelve datos personales.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: VersionDePlantillaResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v16.1 §22.2 · REG-06-209',
  },
  {
    // El 09 declara `SESSION_MFA` (09:1466); se implementa como `SESSION` en esta demo sintética, mismo tratamiento
    // que WP-06 (DL-088 #17): «08 §25 deja el segundo factor opcional en la demo sintética».
    id: 'API-FRM-03',
    metodo: 'post',
    ruta: '/advisees/{adviseeId}/form-requests',
    resumen: 'Crear una Solicitud de información pertinente. Una plantilla con campos más amplios no amplía B2: cada categoría/campo pedido se valida contra Vínculo+Alcance+B2 vigentes en la misma transacción.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: CrearSolicitudDeFormularioRequestSchema,
    exitos: [{ status: 201, schema: SolicitudDeFormularioCreadaResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['IDEMPOTENCY_KEY_REUSED'],
      422: ['FORM_TEMPLATE_NOT_SELECTABLE', 'FORM_REQUEST_NOT_ALLOWED', 'FORM_REQUEST_INVALID'],
    },
    fuente: '09v16.1 §22.3 · REG-06-210 · TEST-FRM-001/002',
  },
  {
    id: 'API-FRM-04',
    metodo: 'get',
    ruta: '/advisees/{adviseeId}/form-requests',
    resumen: 'Las Solicitudes del profesional autenticado sobre este asesorado. Solo devuelve las actualmente revelables: no hay lectura residual por autoría.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [LIMIT, CURSOR, { nombre: 'status', descripcion: 'Filtra por estado.', schema: { type: 'string', enum: ['PENDING', 'RESPONDED'] } }],
    exitos: [{ status: 200, schema: ListaDeSolicitudesResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v16.1 §22.4 · REG-06-213',
  },
  {
    id: 'API-FRM-05',
    metodo: 'get',
    ruta: '/form-requests/{formRequestId}',
    resumen: 'Una Solicitud, en la proyección del actor que consulta: el profesional solo si el PDP lo sigue permitiendo (si no, el mismo 404 que una inexistente), el asesorado siempre para lo propio. La respuesta nunca expone autorizaciones internas ajenas.',
    autenticacion: 'SESSION',
    idempotencia: false,
    exitos: [{ status: 200, schema: DetalleDeSolicitudResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST'], 404: ['RESOURCE_NOT_FOUND'] },
    fuente: '09v16.1 §22.5 · REG-06-213 · TEST-FRM-007',
  },
  {
    id: 'API-FRM-06',
    metodo: 'get',
    ruta: '/me/form-requests',
    resumen: 'Las Solicitudes propias del actor autenticado, con `respondable` calculado por el PDP en esta misma lectura — no es un tercer estado de la Solicitud.',
    autenticacion: 'SESSION',
    idempotencia: false,
    query: [LIMIT, CURSOR, { nombre: 'status', descripcion: 'Filtra por estado.', schema: { type: 'string', enum: ['PENDING', 'RESPONDED'] } }],
    exitos: [{ status: 200, schema: ListaDeSolicitudesPropiasResponseSchema }],
    errores: { ...SESION, 400: ['INVALID_REQUEST', 'INVALID_CURSOR'] },
    fuente: '09v16.1 §22.6 · REG-06-213',
  },
  {
    id: 'API-FRM-07',
    metodo: 'post',
    ruta: '/me/form-requests/{formRequestId}/responses',
    resumen: 'Enviar la respuesta propia. Cada respuesta queda SELF_REPORTED; un campo opcional que no se responde se omite, nunca cero/default; no crea consentimiento ni reabre vínculo.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: EnviarRespuestaRequestSchema,
    exitos: [{ status: 201, schema: RespuestaCreadaResponseSchema }],
    // FORM_RESPONSE_INVALID no está en el 09 para FRM-07 (solo lo declara para FRM-08), pero es la misma forma que
    // valida FRM-08 y DL-095 ya lo registra como forma no fijada: un campo fuera de tipo o de lo solicitado tiene
    // que rechazarse en las dos, no solo al rectificar.
    errores: { ...ESCRITURA_REVELABLE, 409: ['IDEMPOTENCY_KEY_REUSED'], 422: ['FORM_REQUEST_NOT_RESPONDABLE', 'FORM_RESPONSE_INVALID'] },
    fuente: '09v16.1 §22.7 · REG-06-211 · TEST-FRM-003/004/005 · DL-095',
  },
  {
    id: 'API-FRM-08',
    metodo: 'post',
    ruta: '/me/form-responses/{formResponseId}/rectifications',
    resumen: 'Rectificar una respuesta propia: crea una sucesora, nunca sobrescribe la original, y mantiene SELF_REPORTED. No restaura la lectura del profesional si el PDP ya no la permite.',
    autenticacion: 'SESSION',
    idempotencia: true,
    request: RectificarRespuestaRequestSchema,
    exitos: [{ status: 201, schema: RectificacionCreadaResponseSchema }],
    errores: {
      ...ESCRITURA_REVELABLE,
      409: ['IDEMPOTENCY_KEY_REUSED', 'VERSION_CONFLICT'],
      422: ['FORM_RESPONSE_RECTIFICATION_NOT_ALLOWED', 'FORM_RESPONSE_INVALID'],
    },
    fuente: '09v16.1 §22.8 · REG-06-211 · TEST-FRM-006',
  },
];

/**
 * Códigos que salen del manejo de concurrencia y de carga, comunes a varias operaciones (revisión adversarial de WP-03):
 * - toda escritura corre en una transacción que se repite ante deadlock o falla de serialización; si persiste, responde
 *   409 RESOURCE_CONFLICT («conflicto concurrente», 09 §3);
 * - las lecturas de un recurso protegido comparten un límite por actor: 429 RATE_LIMITED.
 */
const LECTURAS_PROTEGIDAS: ReadonlySet<string> = new Set([
  'API-DSH-03',
  'API-ANT-03',
  'API-ANT-06',
  'API-ANT-06-PROPIA',
  'API-ANT-08',
  'API-ANT-09',
  'API-CAL-02',
  'API-CAL-03',
  'API-REL-06',
  'API-CON-01',
  'API-NUT-02',
  'API-NUT-03',
  'API-NUT-05',
  'API-NUT-06',
  'API-NUT-08',
  'API-NUT-09',
  'API-NUT-16',
  'API-NUT-17',
  'API-NUT-19',
  'API-TRN-02',
  'API-TRN-03',
  'API-TRN-05',
  'API-TRN-06',
  'API-TRN-08',
  'API-TRN-09',
  'API-TRN-19',
  'API-TRN-21',
  'API-TRN-23',
  'API-FRM-04',
  'API-FRM-05',
  'API-FRM-06',
]);
const ESCRITURAS_SIN_CLAVE: ReadonlySet<string> = new Set(['API-CON-04', 'API-CON-08', 'API-NUT-10', 'API-NUT-11', 'API-ANT-10', 'API-TRN-10', 'API-TRN-11', 'API-TRN-15', 'API-TRN-17']);

function conCodigosComunes(op: Operacion): Operacion {
  const errores: { -readonly [S in keyof Errores]: Errores[S] } = { ...op.errores };
  const sumar = (status: 409 | 429, codigo: Codigo) => {
    const actuales = errores[status] ?? [];
    if (!actuales.includes(codigo)) errores[status] = [...actuales, codigo];
  };
  if (op.idempotencia || ESCRITURAS_SIN_CLAVE.has(op.id)) sumar(409, 'RESOURCE_CONFLICT');
  if (LECTURAS_PROTEGIDAS.has(op.id)) sumar(429, 'RATE_LIMITED');
  return { ...op, errores };
}

export const OPERACIONES: readonly Operacion[] = DEFINIDAS.map(conCodigosComunes);

const aJson = (schema: z.ZodType) => z.toJSONSchema(schema, { target: 'draft-2020-12', io: 'input' });

export function documentoOpenApi(): Record<string, unknown> {
  const paths: Record<string, Record<string, unknown>> = {};
  for (const op of OPERACIONES) {
    const parametros: Record<string, unknown>[] = [];
    for (const [, nombre] of op.ruta.matchAll(/\{([^}]+)\}/g)) {
      parametros.push({ name: nombre, in: 'path', required: true, schema: { type: 'string' } });
    }
    if (op.idempotencia) {
      parametros.push({
        name: 'Idempotency-Key',
        in: 'header',
        required: true,
        schema: { type: 'string', pattern: '^[A-Za-z0-9._:-]{8,128}$' },
      });
    }
    for (const q of op.query ?? []) {
      parametros.push({ name: q.nombre, in: 'query', required: q.obligatorio === true, description: q.descripcion, schema: q.schema });
    }
    parametros.push({
      name: 'X-BE-Surface',
      in: 'header',
      required: false,
      description: 'Superficie declarada (procedencia). Nunca autoriza (DEUDA_LEGAJO DL-022).',
      schema: { type: 'string', enum: ['WEB', 'APK'] },
    });
    const respuestas: Record<string, unknown> = {};
    for (const exito of op.exitos) {
      respuestas[exito.status] = exito.schema
        ? { description: 'Éxito', content: { 'application/json': { schema: aJson(exito.schema) } } }
        : { description: 'Éxito, sin cuerpo' };
    }
    for (const [status, codigos] of Object.entries(conComunes(op.errores))) {
      respuestas[status] = {
        description: `ErrorEnvelope: ${(codigos ?? []).join(' | ')}`,
        content: { 'application/json': { schema: { $ref: '#/components/schemas/ErrorEnvelope' } } },
      };
    }
    paths[op.ruta] = {
      ...paths[op.ruta],
      [op.metodo]: {
        operationId: op.id,
        summary: op.resumen,
        description: `Fuente: ${op.fuente}. AuthN: ${op.autenticacion}.`,
        security: op.autenticacion === 'PUBLIC' ? [] : [{ sesion: [] }],
        parameters: parametros,
        ...(op.request
          ? { requestBody: { required: op.requestOpcional !== true, content: { 'application/json': { schema: aJson(op.request) } } } }
          : {}),
        responses: respuestas,
      },
    };
  }
  return {
    openapi: '3.1.0',
    info: {
      title:
        'BE API — WP-02 Identidad y sesiones · WP-03 Vínculo, consentimiento y PDP · WP-04 Circuito nutricional · WP-05 Antropometría, métodos y cálculos · WP-06 Circuito de entrenamiento · WP-07 Información profesional pertinente · WP-08 Integraciones P0',
      version: '0.10.0',
      description:
        'Generado desde @be/domain (contratos.ts, contratos-vinculo.ts, contratos-nutricion.ts, contratos-antropometria.ts, contratos-calculo.ts, contratos-entrenamiento.ts, contratos-formularios.ts, contratos-procedencia-externa.ts y contratos-integraciones.ts). No editar a mano.',
    },
    servers: [{ url: '/api/v1' }],
    components: {
      securitySchemes: {
        sesion: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT', description: 'Sesión revocable verificada en cada request (08 §26).' },
      },
      schemas: { ErrorEnvelope: aJson(ErrorEnvelopeSchema) },
    },
    paths,
  };
}

/** Códigos de error declarados para una operación (los propios más los comunes), por status. Lo usa el contract test. */
export function erroresDeclarados(id: string): Readonly<Record<string, readonly string[]>> {
  const op = OPERACIONES.find((o) => o.id === id);
  if (!op) throw new Error(`Operación no declarada: ${id}`);
  return conComunes(op.errores);
}

/** Busca la operación de una request real (método + ruta concreta con parámetros). Lo usa el contract test. */
export function operacionDe(metodo: string, rutaConcreta: string): Operacion | undefined {
  return OPERACIONES.find((o) => {
    if (o.metodo !== metodo) return false;
    const patron = new RegExp(`^/api/v1${o.ruta.replace(/\{[^}]+\}/g, '[^/]+')}$`);
    return patron.test(rutaConcreta);
  });
}
